# Generated by Django 5.0.3 on 2024-03-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author_remove_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voetbalspeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('club', models.CharField(max_length=255)),
                ('auteur', models.CharField(max_length=255)),
                ('datum_invoer', models.DateTimeField(auto_now_add=True)),
                ('datum_laatste_aanpassing', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
